[reality_nodes]
# Ansible 会自动去 ssh config 找 "dcc" 的配置
dzire ansible_python_interpreter=/usr/bin/python3
legend ansible_python_interpreter=/usr/bin/python3
netcup ansible_python_interpreter=/usr/bin/python3

# 强制指定 ansible_user=root
#kagoya ansible_host=kagoya的IP地址 ansible_user=root ansible_python_interpreter=/usr/bin/python3
kagoya ansible_python_interpreter=/usr/bin/python3
ams ansible_python_interpreter=/usr/bin/python3
dcc ansible_python_interpreter=/usr/bin/python3

# 本机 (新增这行)
# 1. ansible_connection=local: 使用本地连接
# 2. ansible_python_interpreter: 显式指定 Python 路径(可选，防止警告)
spt ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[free]
netcup
dzire
legend

[normal]
spt
kagoya

[premium]
ams
dcc
