[reality_nodes]
dzire ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "dzire" 的配置

netcup ansible_python_interpreter=/usr/bin/python3 # canonical: netcup；连接使用 ssh config 的 "netcup"

# 强制指定 ansible_user=root
#kagoya ansible_host=kagoya的IP地址 ansible_user=root ansible_python_interpreter=/usr/bin/python3
#kagoya ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "kagoya" 的配置

ams ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "ams" 的配置

dcc ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "dcc" 的配置

legend ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "legend" 的配置
jp05 ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "jp05" 的配置

hk01 ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "hk01" 的配置
hk02 ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "hk02" 的配置
jp10 ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "jp10" 的配置

kagoya ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "kagoya" 的配置
usca ansible_python_interpreter=/usr/bin/python3 # Ansible 会自动去 ssh config 找 "usca" 的配置
# 本机 (新增这行)
# 1. ansible_connection=local: 使用本地连接
# 2. ansible_python_interpreter: 显式指定 Python 路径(可选，防止警告)
spt ansible_connection=local ansible_python_interpreter=/usr/bin/python3

# --- 层级规则 ---
[free]
dzire
usca
netcup

[basic]
jp05
legend
kagoya

[normal]
jp10
hk01

[premium]
ams
dcc
hk02

# --- 特性规则 (按需扩展) ---
[special]
spt
