# 统一的组变量（推荐通过该文件加载）

xray_image: "taoziyoyo2566/xray_docker:latest"
domain_suffix: "taoziyoyo.com"
server_hash_suffix: "o9drrm5l1d7uopaguucnxohzc3ul2yazxrldzpuoduu"
reality_server_names: ["www.apple.com", "images.apple.com"]
reality_dest: "www.apple.com:443"
reality_data_dir: "/opt/data"
monitor_root_dir: "/opt/monitor"
monitor_venv_dir: "{{ monitor_root_dir }}/venv"

# --- 监控系统配置 ---
monitor:
  server_host: "spt"           # 指定 Inventory 中哪台机器跑数据库
  server_url: "https://monitor.taoziyoyo.com"   # 上报 / stats / docs
  subs_base_url: "https://subs.taoziyoyo.com"   # 订阅代理
  # 内部监听地址 (仅限本机)
  internal_host: "127.0.0.1"
  internal_port: 8000
  port: 8000                   # 监控服务端口
  report_token: "{{ vault_monitor_report_token | default('CHANGEME-report-token') }}"   # 上报认证 Token（Vault）
  admin_bearer_token: "{{ vault_monitor_admin_bearer_token | default('CHANGEME-admin-bearer') }}" # 管理员 Bearer，用于 stats/doc
  stats_bearer_token: "{{ vault_monitor_stats_bearer_token | default('CHANGEME-stats-bearer') }}" # 普通 Bearer，用于只读 stats
  ip_allowlist: ["127.0.0.1","45.145.75.134","133.18.123.108","49.98.151.252","2604:9cc0:1cb1:0:91ae:5c39:e233:4081","160.191.29.7","2607:8700:5500:32ec::2","2a00:11c0:47:1c95:8868:d8ff:fed5:bc4d"]   # 允许免认证的 IP（CF/内网）
  # trust_proxy_header: "CF-Connecting-IP"  # 从哪一个头部拿真实客户端 IP，CF 默认 CF-Connecting-IP
  trust_proxy_header: "X-Forwarded-For"
  subs_proxy:
    enabled: true               # 是否启用订阅访问记录代理
    gist_user: "{{ vault_monitor_gist_user | default('taoziyoyo2566') }}"
    gist_id: "{{ vault_monitor_gist_id | default('0a7faae910b06151d643c7d5baa43818') }}"
    require_token: true          # 访问订阅代理时是否需要 token
    token: "{{ vault_monitor_subs_token | default('CHANGEME-subs-token') }}"
